fragment PostFields on Post {
	id
	title
	slug
	date
	content
	excerpt
	categories {
		nodes {
			id
			name
			slug
		}
	}
	featuredImage {
		node {
			...MediaItemFields
		}
	}
	postMeta {
		relatedWorks {
			edges {
				node {
					... on Work {
						slug
						title
						date
						featuredImage {
							node {
								...MediaItemFields
							}
						}
					}
				}
			}
		}
	}
}
