fragment WorkFields on Work {
	id
	title
	slug
	date
	content
	workFields {
		excerpt
		githubUrl
		siteUrl
		at
		role
		year
	}
	categories {
		nodes {
			id
			name
			slug
		}
	}
	featuredImage {
		node {
			sourceUrl
			altText
		}
	}
}
